providers = ["node"]
name = "newbcar"
pkg_manager = "pnpm"

[phases.setup]
nixpkgs = ["nodejs_22", "pnpm"]

[phases.install]
command = "pnpm install"

[phases.build]
command = "pnpm run build"

[phases.start]
command = "pnpm start"
